language: node_js
node_js:
  - lts/*
install:
  - npm install
script:
  - npm run build
cache: npm
deploy:
  edge:
    branch: v1.8.47
  provider: pages
  skip-cleanup: true
  keep-history: true
  local-dir: dist
  github-token: $GITHUB_TOKEN
  on:
    branch: master
