language: node_js
node_js:
  - lts/*
install:
  - npm install
script:
  - npm build
cache: npm
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  local-dir: dist
  on:
    branch: master
  github-token: $GITHUB_TOKEN
