language: node_js
node_js:
  - lts/*
install:
  - npm install
script:
  - npm run build
env:
  - PUBLIC_PATH: https://meijjj.github.io/table_component/
  - NO_LOGIN: 1
  - MODE: mock
cache: npm
deploy:
  edge:
    branch: v1.8.47
  provider: pages
  skip-cleanup: true
  keep-history: true
  local-dir: dist
  github-token: $GITHUB_TOKEN
  on:
    branch: master
