language: node_js
node_js:
  - lts/*
install:
  - npm install
script:
  - npm run build
env:
  global:
    - PUBLIC_PATH=https://meijjj.github.io/table_component/
    - NO_LOGIN=1
    - MODE=mock
cache: npm
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  local-dir: dist
  github-token: $GITHUB_TOKEN
  on:
    branch: master
